name: conduit_mysql
description: The mysql ORM for conduit.
version: 4.3.2-alpha
repository: https://github.com/conduit-dart/conduit

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  conduit_core: ^4.3.0
  mysql1: ^0.20.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.6